"""Decision-support models for course-of-action recommendations."""

from datetime import datetime
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


class DecisionRecommendation(BaseModel):
    """A recommended course of action generated by the Decision Support Agent."""

    model_config = ConfigDict(frozen=True)

    recommendation_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique recommendation identifier",
    )
    recommended_actions: list[str] = Field(
        ..., min_length=1, description="Ordered list of recommended actions"
    )
    priority: int = Field(..., ge=1, le=5, description="Priority 1 (highest) to 5 (lowest)")
    reason: str = Field(..., min_length=1, description="Rationale for this recommendation")


class CommanderDecision(BaseModel):
    """The commander's final decision in response to a recommendation."""

    model_config = ConfigDict(frozen=True)

    decision: str = Field(
        ..., min_length=1, description="The commander's chosen course of action"
    )
    decision_time: datetime = Field(..., description="When the decision was recorded")
    operator_name: str = Field(
        ..., min_length=1, description="Name or identifier of the decision-maker"
    )
    remarks: str | None = Field(None, description="Optional remarks from the commander")
